# Generated by Django 4.2.24 on 2025-12-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='keywords',
            field=models.TextField(blank=True, help_text='Separe as palavras-chave por ponto e vírgula (;)'),
        ),
    ]
