# Generated by Django 4.2.24 on 2025-12-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal da notícia (máx. 200 caracteres)', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título', max_length=220, unique=True, verbose_name='URL amigável')),
                ('resumo', models.CharField(help_text='Breve descrição que aparece no carrossel e cards (máx. 300 caracteres)', max_length=300, verbose_name='Resumo/Descrição')),
                ('banner_pequeno', models.ImageField(help_text='Imagem para cards de notícias (recomendado: 400x300px)', upload_to='noticias/thumbnails/%Y/%m/', verbose_name='Banner Pequeno (Card)')),
                ('banner_carrossel', models.ImageField(help_text='Imagem para o carrossel principal (recomendado: 1200x400px)', upload_to='noticias/banners/%Y/%m/', verbose_name='Banner Carrossel')),
                ('corpo_da_noticia', models.TextField(help_text='Conteúdo completo da notícia', verbose_name='Corpo da Notícia')),
                ('links_uteis', models.TextField(blank=True, help_text='Links relacionados (um por linha ou formato JSON)', null=True, verbose_name='Links Úteis')),
                ('autor', models.CharField(default='Secretaria da Fazenda', help_text='Nome do autor ou órgão responsável', max_length=100, verbose_name='Autor')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativa', models.BooleanField(default=True, help_text='Desmarque para ocultar a notícia do site', verbose_name='Ativa')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para exibir esta notícia no carrossel principal', verbose_name='Destaque')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para motores de busca (máx. 160 caracteres)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255, verbose_name='Meta Keywords')),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Visualizações')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-dt_inclusao', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaginasRelacionadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Aparece ao passar o mouse', max_length=100)),
                ('imagem', models.ImageField(upload_to='paginasrelacionadas/')),
                ('link', models.URLField()),
            ],
        ),
    ]
