# Generated by Django 4.2.27 on 2025-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_noticia_paginasrelacionadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcessoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('icone', models.CharField(help_text="Coloque aqui o nome da classe do ícone FontAwesome. Ex: 'fa-solid fa-book-open'", max_length=50)),
            ],
        ),
    ]
