# Generated by Django 4.2.24 on 2025-12-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_acessorapido'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRodape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('url', models.URLField(help_text='Ex: https://seusite.com.br/pagina', verbose_name='Link de redirecionamento')),
                ('tipo', models.CharField(choices=[('PLATAFORMA', 'Plataforma'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('abrir_em_nova_aba', models.BooleanField(default=False, verbose_name='Abrir em nova aba?')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Link do rodapé',
                'verbose_name_plural': 'Links do rodapé',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(default='Prefeitura de Nova Friburgo', max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, help_text='Ex: 5522999999999 (somente números)', max_length=30, null=True, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail institucional')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço completo com horário de funcionamento')),
                ('link_instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('link_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('link_youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
                ('link_site', models.URLField(blank=True, null=True, verbose_name='Website oficial')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
