# Generated by Django 4.2.24 on 2026-01-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_linkrodape_siteconfiguracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiasFazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal da notícia (máx. 200 caracteres)', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Gerado automaticamente a partir do título', max_length=220, unique=True, verbose_name='URL amigável')),
                ('resumo', models.CharField(help_text='Breve descrição que aparece no carrossel e cards (máx. 300 caracteres)', max_length=300, verbose_name='Resumo/Descrição')),
                ('banner_pequeno', models.ImageField(help_text='Imagem para cards de notícias (recomendado: 400x300px)', upload_to='noticias/thumbnails/%Y/%m/', verbose_name='Banner Pequeno (Card)')),
                ('banner_carrossel', models.ImageField(help_text='Imagem para o carrossel principal (recomendado: 1200x400px)', upload_to='noticias/banners/%Y/%m/', verbose_name='Banner Carrossel')),
                ('corpo_da_noticia', models.TextField(help_text='Conteúdo completo da notícia', verbose_name='Corpo da Notícia')),
                ('links_uteis', models.TextField(blank=True, help_text='Links relacionados (um por linha ou formato JSON)', null=True, verbose_name='Links Úteis')),
                ('autor', models.CharField(default='Secretaria da Fazenda', help_text='Nome do autor ou órgão responsável', max_length=100, verbose_name='Autor')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativa', models.BooleanField(default=True, help_text='Desmarque para ocultar a notícia do site', verbose_name='Ativa')),
                ('destaque', models.BooleanField(default=False, help_text='Marque para exibir esta notícia no carrossel principal', verbose_name='Destaque')),
                ('meta_description', models.CharField(blank=True, help_text='Descrição para motores de busca (máx. 160 caracteres)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula', max_length=255, verbose_name='Meta Keywords')),
                ('visualizacoes', models.PositiveIntegerField(default=0, editable=False, verbose_name='Visualizações')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-dt_inclusao', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['id', 'titulo'], 'verbose_name': 'Notícia_Legado', 'verbose_name_plural': 'Notícias_Legado'},
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='banner_carrossel',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='banner_pequeno',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='destaque',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='dt_atualizacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='dt_inclusao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='links_uteis',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='visualizacoes',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='corpo_da_noticia',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
