# Generated by Django 4.2.24 on 2026-01-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_noticiasfazenda_alter_noticia_options_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='noticiasfazenda',
            name='ordem_carrossel',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição no carrossel principal (0 = não exibe)', verbose_name='Ordem no Carrossel'),
        ),
    ]
