# Generated by Django 4.2.27 on 2026-01-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0006_remove_noticia_ativa_remove_noticia_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='banner_carrossel',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='banner_pequeno',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='destaque',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='dt_atualizacao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='dt_inclusao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='links_uteis',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='visualizacoes',
        ),
    ]
