# Generated by Django 4.2.27 on 2026-01-13 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financas', '0007_remove_noticia_ativa_remove_noticia_autor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(choices=[('alvara', 'Alvará'), ('iptu', 'IPTU/Foro'), ('isencao', 'Isenção/Imunidade'), ('itbi', 'ITBI'), ('certidoes', 'Certidões e Averbações'), ('requerimentos', 'Requerimentos Diversos')], help_text='Escolha em qual seção o formulário será exibido', max_length=20, verbose_name='Categoria do Formulário')),
                ('titulo', models.CharField(help_text='Nome que aparecerá para o usuário (ex: Requerimento de Alvará.pdf)', max_length=255, verbose_name='Título do Formulário')),
                ('arquivo', models.FileField(help_text='Envie o arquivo PDF do formulário', upload_to='formularios/%Y/%m/', verbose_name='Arquivo PDF')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Número menor aparece primeiro', verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField(auto_now=True)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FormularioUserInclusao', to=settings.AUTH_USER_MODEL)),
                ('user_ultima_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FormularioUserAlteracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formulário Download',
                'verbose_name_plural': 'Formulários Download',
                'ordering': ['classe', 'ordem'],
            },
        ),
    ]
