# Generated by Django 4.2.27 on 2026-01-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0008_formulariodownload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormularioDownload',
        ),
    ]
