# Generated by Django 4.2.27 on 2026-01-13 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0009_delete_formulariodownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe_Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('div_id', models.CharField(max_length=10)),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='formularios/', verbose_name='Arquivo do Formulário')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.classe_formulario')),
            ],
        ),
    ]
