# Generated by Django 4.2.27 on 2026-01-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0010_classe_formulario_formularios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe_formulario',
            options={'verbose_name': 'Classe Formulário', 'verbose_name_plural': 'Classes Formulários'},
        ),
        migrations.AlterModelOptions(
            name='formularios',
            options={'verbose_name': 'Formulário', 'verbose_name_plural': 'Formulários'},
        ),
        migrations.AlterModelOptions(
            name='paginasrelacionadas',
            options={'verbose_name': 'Página Relacionada', 'verbose_name_plural': 'Páginas Relacionadas'},
        ),
        migrations.AlterField(
            model_name='noticiasfazenda',
            name='banner_pequeno',
            field=models.ImageField(help_text='Imagem para cards de notícias (recomendado: 400x165px)', upload_to='noticias/thumbnails/%Y/%m/', verbose_name='Banner Pequeno (Card)'),
        ),
    ]
